# Generated by Django 2.2.24 on 2021-09-01 03:40

import api_app.models
import api_app.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_auto_20210901_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img',
            field=models.ImageField(storage=api_app.storage.OverwriteStorage(), upload_to=api_app.models.upload_path),
        ),
    ]
